version: '3.1'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  subscribe:
    build: .
    command: ["npm", "run", "subscribe"]
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  publish:
    build: .
    command: ["npm", "run", "publish"]
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      - subscribe
